### ISSUE TITLE
python module curses missing

### ISSUE THREAD

**Issue by morfeus77** [MiSTer-devel/Linux-Kernel_MiSTer_old#29]
Would it be possible to have the curses python module available?  The benefit of providing this python module would be that it enables text-based ui scripts written in Python whereas now it's only achievable in bash or by wrapping the linux dialog utility.

**Comment by sorgelig** [comment]
will be included in upcoming release

**Comment by morfeus77** [comment]
zlib module also missing, might be useful to use tar.gz files without having to call a bash subprocess

**Comment by sorgelig** [comment]
added both curses and zlib
